In [1]:
# Import the needed libraries
import numpy as np

**72. How to swap two rows of an array?** 

In [3]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array[[0,1]] = array[[1, 0]]

In [5]:
array

array([[4, 5, 6],
       [1, 2, 3]])

**75. How to compute averages using a sliding window over an array?**

If you interpreted it as a way to compute the average of the whole list than the solution is:

In [6]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
(np.cumsum(array)/len(array))[-1]

5.5

Instead, implementing a moving average:

In [17]:
def moving_average(a, window_size=3):
    sums = np.cumsum(a)
    sums[window_size:] = sums[window_size:] - sums[:-window_size]
    return sums[window_size-1:]/window_size

In [19]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
moving_average(array)

array([2., 3., 4., 5., 6., 7., 8., 9.])