# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [1]:
import numpy as np

In [2]:
def add_vectors(u, v):
    return np.add(u,v)
    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """
add_vectors([1, 0], [1, 1])
add_vectors([1, 2], [1, 4])

array([2, 6])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [4]:
#without numpy
def scalar_mult(s, v):
    m=[]
    for x in v:
        m.append(s*x)
    return m
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """
scalar_mult(5, [1, 2])

[5, 10]

In [3]:
#with np
def scalar_mult_np(s, v):
    return s*np.array(v)
scalar_mult_np(5, [1, 2])

array([ 5, 10])

One thing to consider here is that using a **list directly would not work**:

In [5]:
[1,2]*5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [43]:
# without numpy
def dot_product(u, v):
    c = [u*v for u,v in zip(u,v)]
    return sum(c)
    """
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
dot_product([1, 1], [1, 1])
#dot_product([1, 2], [1, 4])
#dot_product([1, 2, 1], [1, 4, 3])
#dot_product([2, 0, -1, 1], [1, 5, 2, 0])

2

In [45]:
#with np
def dot_product_np(a,b):
    return np.dot(a,b)
dot_product_np([1, 1], [1, 1])

2

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [9]:
def copy_matrix(matrix):
    return matrix.copy()
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
copy_matrix([[1, 2], [3, 4]])

[[1, 2], [3, 4]]

In [46]:
#using vstack
def add_row(matrix):
    m=[]
    for x in matrix:
        a=len(x)
    for i in range(a):
        m.append(0)
    return np.vstack([matrix,m])
    
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    
n = [[3, 2, 5], [1, 4, 7]]
add_row(n)


array([[3, 2, 5],
       [1, 4, 7],
       [0, 0, 0]])

one thing to take in consideration is that we don't modify the **original matrix**; 
if we want to save we should save in **other variable name**

In [22]:
#more fast with directly using vstack if we use the
def add_row_np(matrix, row):
    return np.vstack([matrix,row])

m = [[0, 0], [0, 0]]
add_row_np(m, [0, 0])

array([[0, 0],
       [0, 0],
       [0, 0]])

In [24]:
#it would probably be a good idea to incorporate a dimensionality check
n=[[3, 2, 5], [1, 4, 7]]
add_row_np(n, [0, 0, 0])

array([[3, 2, 5],
       [1, 4, 7],
       [0, 0, 0]])

In [25]:
#from scratch
def add_column(matrix):
    m=[]
    a=len(matrix)
    for i in range(a):
        m.append(0)
    return np.column_stack([matrix,m])

    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """

n = [[3, 2], [5, 1], [4, 7]]
add_column(n)

array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

In [26]:
#using NP
def add_column_np(matrix,col):
    return np.column_stack([matrix,col])
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """
n = [[3, 2], [5, 1], [4, 7]]
add_column_np(n,[0,0,0])

array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [30]:
#working with np arrays
#you can also do it with lists but it is hard to keep track of the dimensions
#numpy gets easier and easier...
def add_matrices(m1, m2):
    m3=[]
    for x,y in zip(m1,m2):
        m3.append(np.add(x,y))
#we then transform the array as a matrix (easier)
    return np.asmatrix(m3)
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """

a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a, b)

matrix([[3, 4],
        [5, 6]])

In [32]:
#same approach, with matrixes directly
def add_matrices_np(a, b):
    a=np.matrix(a)
    b=np.matrix(b)
    #we could double check it is a matrix and so on
    return a+b
add_matrices_np(a, b)

matrix([[3, 4],
        [5, 6]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [48]:
# numpy
def scalar_mult(s, m):
    m=np.matrix(m)
    return s*m

    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """
a = [[1, 2], [3, 4]]
scalar_mult(3, a)

matrix([[ 3,  6],
        [ 9, 12]])

In [62]:
def scalar_mult_flt(s, m):
    m = np.matrix(m)
    dim = np.shape(m)
    v = m.flatten()
    nv = v*s
    return np.matrix(nv.reshape(dim))
    
scalar_mult_flt(3, a)
# [1, 2, 3, 4]

matrix([[ 3,  6],
        [ 9, 12]])

In [35]:
# from scratch: you could do a double nest and multiply, just make sure to turn it into a list of lists afterwards (Matrix)

# to explain better
Write functions row_times_column and matrix_mult:

In [42]:
def row_times_column(m1, row, m2, column):
    a=np.matmul(m1, m2)
    return  a[row][column]

    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)

19

In [10]:
def matrix_mult(m1, m2):
    a=np.matmul(m1, m2)
    return  a

   """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [40]:
def transpose(m):
    return np.transpose(m)
    """
     >>> m = [[3, 4, 6]]
     >>> transpose(m)
     [[3], [4], [6]]
     >>> m
     [3, 4, 6]
     >>> m = [[3, 4, 6], [1, 5, 9]]
     >>> transpose(m)
     [[3, 1], [4, 5], [6, 9]]
    """
    
m = [[3, 4, 6]]
transpose(m)

array([[3],
       [4],
       [6]])

In [67]:
def transpose_np(m):
    m = np.array(m)
    return m.T

In [68]:
m = [[3, 4, 6]]
transpose_np(m)

array([[3],
       [4],
       [6]])

# TODO
## Give more accurate examples of how this applies to images in the DL space